name: transformer
embed_dim: 768
depth: 2
num_heads: 12
mlp_ratio: 4.0
qkv_bias: true
ffn_bias: true
proj_bias: true
drop_path_rate: 0.0
drop_path_uniform: false
use_memory_efficient: false
init_values: 1.0